name: Deploy to Hostinger VPS

on:
  push:
    branches:
      - main # The branch you want to trigger deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Hostinger VPS
        uses: hostinger/deploy-on-vps@v1
        with:
          api-key: ${{ secrets.VaU00gysvcvGx1KBl3LnkTxjnRrc6Ug976GVhcwO8a70aa03 }}
          virtual-machine: ${{ variables.1200004 }}
          # Optional: specify project name if you have multiple projects on the VPS
          # project-name: your-project-name
          # Optional: pass environment variables
          # environment-variables: |
          #   KEY=value
          #   ANOTHER_KEY=another_value
